# WARNING: you are on the master branch, please refer to the examples on the branch that matches your `cortex version`

- name: text-generator
  kind: SyncAPI
  predictor:
    type: tensorflow
    path: predictor.py
    model_path: s3://cortex-examples/tensorflow/text-generator/gpt-2/124M
    batch_size: 2
    batch_timeout: 1.0
    processes_per_replica: 1
    threads_per_process: 4
  compute:
    cpu: 3
    gpu: 1
